version: '3.7'

services:
  m152-frontend:
    container_name: m152-frontend
    hostname: m152-frontend
    restart: always
    expose:
    - "80"
    build:
      context: ./frontend/m152
      dockerfile: Dockerfile
    networks: 
      - reverse-proxy-network
    volumes: 
      - /.docker_data/m152-frontend/logs:/var/log/nginx

networks:
  reverse-proxy-network:
      name: reverse-proxy-network